export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        ======루트 레이아웃 시작=====
        {children}
        ======루트 레이아웃 끝=====
        </body>
    </html>
  )
}
